# Dependences

In [350]:
include("../../src/struct_data.jl")

fusion_agg (generic function with 1 method)

# Input Data

In [ ]:
X = Float64.(readdlm("../../data/init/Sphere/15.0.xyz")[3:end,2:end])
Y = Float64.(readdlm("../../data/init/Sphere/10.0.xyz")[3:end,2:end])

# Force Functions

## Cubic

In [351]:
@make_struct_func Cubic
dump(Cubic)

UnionAll
  var: TypeVar
    name: Symbol T
    lb: Union{}
    ub: Any
  body: Cubic{T} <: ForceType
    μ₁::T
    rₘᵢₙ::T
    rₘₐₓ::T


In [352]:
# Parameters
μ₁   = 1.0
rₘₐₓ = 2.0
rₘᵢₙ = 3.0
fₚ   = 0.1

0.1

In [353]:
Cubic(μ₁,rₘₐₓ,rₘᵢₙ)

Cubic{Float64}(1.0, 2.0, 3.0)

In [354]:
# Show function on specific r value
r = 1
force_func(Cubic(μ₁,rₘₐₓ,rₘᵢₙ),r)

4.0

In [355]:
dump(
        InteractionPar(
        Cubic(μ₁,rₘₐₓ,rₘᵢₙ),
        ContractilePar(fₚ)
    )
)

InteractionPar
  Force: Cubic{Float64}
    μ₁: Float64 1.0
    rₘᵢₙ: Float64 2.0
    rₘₐₓ: Float64 3.0
  Contractile: ContractilePar
    fₚ: Float64 0.1


## LennardJones

In [356]:
@make_struct_func LennardJones
dump(LennardJones)

UnionAll
  var: TypeVar
    name: Symbol T
    lb: Union{}
    ub: Any
  body: LennardJones{T} <: ForceType
    μ₁::T
    rₘᵢₙ::T
    rₘₐₓ::T


In [357]:
# Parameters
μ₁   = 1.0
rₘₐₓ = 2.0
rₘᵢₙ = 3.0

3.0

In [358]:
LennardJones(μ₁,rₘₐₓ,rₘᵢₙ)

LennardJones{Float64}(1.0, 2.0, 3.0)

In [359]:
# Show function on specific r value
r = 1.9
force_func(LennardJones(μ₁,rₘₐₓ,rₘᵢₙ),r)

1.9609746568876094

In [360]:
dump(
    InteractionPar(
        LennardJones(μ₁,rₘₐₓ,rₘᵢₙ),
        ContractilePar(fₚ)
    )
)

InteractionPar
  Force: LennardJones{Float64}
    μ₁: Float64 1.0
    rₘᵢₙ: Float64 2.0
    rₘₐₓ: Float64 3.0
  Contractile: ContractilePar
    fₚ: Float64 0.1


# Model Parameter

In [362]:
Model = ModelSet(
    TimeModel(
        tₛᵢₘ  = 10000.0,
        dt    = 0.5,
        nₖₙₙ  = 50,
        nₛₐᵥₑ = 100
    ),
    InputModel(
        outer_ratio = 0.8,
        path_input = "../../data/init/Sphere"
    )
)
dump(Model)

ModelSet
  Time: TimeModel
    tₛᵢₘ: Float64 10000.0
    dt: Float64 0.5
    nₖₙₙ: Int64 50
    nₛₐᵥₑ: Int64 100
  Input: InputModel
    outer_ratio: Float64 0.8
    path_input: String "../../data/init/Sphere"


# Aggregate

## Aggregate

In [363]:
dump(
    Aggregate(
        "A", 
        X, 
        InteractionPar(
            Cubic(1.0,2.0,3.0), 
            ContractilePar(0.01)
        ),
        Model
    )
)

Aggregate
  Name: String "A"
  Position: Array{Float64}((2504, 3)) [-1.5 -4.62 -13.88; 0.5 -4.62 -13.88; … ; 0.5 4.62 13.88; 2.5 4.62 13.88]
  Interaction: InteractionPar
    Force: Cubic{Float64}
      μ₁: Float64 1.0
      rₘᵢₙ: Float64 2.0
      rₘₐₓ: Float64 3.0
    Contractile: ContractilePar
      fₚ: Float64 0.01
  Radius: Float64 15.270000000000001
  Outline: Array{Int64}((2504,)) [1, 1, 1, 1, 1, 1, 1, 1, 1, 1  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


## Simple Aggregate

In [364]:
@time AllAggs = AllAggregates(
    [Aggregate("A", X, InteractionPar(Cubic(1.0,2.0,3.0), ContractilePar(0.01)), Model)]
    ,
    [
        ["A",[100 ,0   ,0  ]],
        ["A",[0   ,100 ,0  ]]
    ]
)
dump(AllAggs)

  0.515869 seconds (648.14 k allocations: 37.653 MiB, 2.91% gc time, 97.91% compilation time)
AllAggregates
  AggType: Array{Any}((1, 4))
    1: Int64 1
    2: String "A"
    3: Float64 15.270000000000001
    4: InteractionPar
      Force: Cubic{Float64}
        μ₁: Float64 1.0
        rₘᵢₙ: Float64 2.0
        rₘₐₓ: Float64 3.0
      Contractile: ContractilePar
        fₚ: Float64 0.01
  AggTypeIdx: Array{Any}((5008, 2))
    1: Int64 1
    2: Int64 1
    3: Int64 1
    4: Int64 1
    5: Int64 1
    ...
    10012: String "A"
    10013: String "A"
    10014: String "A"
    10015: String "A"
    10016: String "A"
  AggIdx: Array{Any}((5008, 2))
    1: Int64 1
    2: Int64 1
    3: Int64 1
    4: Int64 1
    5: Int64 1
    ...
    10012: String "A"
    10013: String "A"
    10014: String "A"
    10015: String "A"
    10016: String "A"
  Position: Array{Float64}((5008, 3)) [98.5 -4.62 -13.88; 100.5 -4.62 -13.88; … ; 0.5 104.62 13.88; 2.5 104.62 13.88]
  Outline: Array{Int64}((5008,)) [1, 1

In [365]:
show_all_aggregates(AllAggs)

===================== AggType ======================


1×4 Matrix{Any}:
 1  …  InteractionPar(Cubic{Float64}(1.0, 2.0, 3.0), ContractilePar(0.01))

=================== AggTypeIdx =====================


5008×2 Matrix{Any}:
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 ⋮  
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"

===================== AggIdx ======================


5008×2 Matrix{Any}:
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 ⋮  
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"

===================== Position ======================


5008×3 Matrix{Float64}:
  98.5   -4.62  -13.88
 100.5   -4.62  -13.88
 102.5   -4.62  -13.88
  95.5   -2.89  -13.88
  97.5   -2.89  -13.88
  99.5   -2.89  -13.88
 101.5   -2.89  -13.88
 103.5   -2.89  -13.88
  94.5   -1.15  -13.88
  96.5   -1.15  -13.88
  98.5   -1.15  -13.88
 100.5   -1.15  -13.88
 102.5   -1.15  -13.88
   ⋮            
  -1.5  101.15   13.88
   0.5  101.15   13.88
   2.5  101.15   13.88
   4.5  101.15   13.88
  -4.5  102.89   13.88
  -2.5  102.89   13.88
  -0.5  102.89   13.88
   1.5  102.89   13.88
   3.5  102.89   13.88
  -1.5  104.62   13.88
   0.5  104.62   13.88
   2.5  104.62   13.88

===================== Outline ======================


5008-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

Outer/Total = 0.46325878594249204


## Complex Aggregate

In [366]:
@time AllAggs = AllAggregates(
    [Aggregate("A", X, InteractionPar(Cubic(1.0,2.0,3.0), ContractilePar(0.01)), Model),
     Aggregate("B", Y, InteractionPar(Cubic(2.0,2.0,3.0), ContractilePar(0.02)), Model),
     Aggregate("C", X, InteractionPar(Cubic(3.0,2.0,3.0), ContractilePar(0.02)), Model),
     Aggregate("D", Y, InteractionPar(Cubic(4.0,2.0,3.0), ContractilePar(0.04)), Model)
    ],
    [
        ["A",[100 ,0   ,0  ]],
        ["C",[0   ,100 ,0  ]],
        ["D",[0   ,0   ,100]],
        ["B",[0   ,100 ,0  ]]
    ]
)
dump(AllAggs)

  0.015129 seconds (123.88 k allocations: 8.943 MiB)
AllAggregates
  AggType: Array{Any}((4, 4))
    1: Int64 1
    2: Int64 2
    3: Int64 3
    4: Int64 4
    5: String "A"
    ...
    12: Float64 10.430000000000001
    13: InteractionPar
      Force: Cubic{Float64}
        μ₁: Float64 1.0
        rₘᵢₙ: Float64 2.0
        rₘₐₓ: Float64 3.0
      Contractile: ContractilePar
        fₚ: Float64 0.01
    14: InteractionPar
      Force: Cubic{Float64}
        μ₁: Float64 2.0
        rₘᵢₙ: Float64 2.0
        rₘₐₓ: Float64 3.0
      Contractile: ContractilePar
        fₚ: Float64 0.02
    15: InteractionPar
      Force: Cubic{Float64}
        μ₁: Float64 3.0
        rₘᵢₙ: Float64 2.0
        rₘₐₓ: Float64 3.0
      Contractile: ContractilePar
        fₚ: Float64 0.02
    16: InteractionPar
      Force: Cubic{Float64}
        μ₁: Float64 4.0
        rₘᵢₙ: Float64 2.0
        rₘₐₓ: Float64 3.0
      Contractile: ContractilePar
        fₚ: Float64 0.04
  AggTypeIdx: Array{Any}((6500, 2))
  

In [367]:
show_all_aggregates(AllAggs)

===================== AggType ======================


4×4 Matrix{Any}:
 1  …  InteractionPar(Cubic{Float64}(1.0, 2.0, 3.0), ContractilePar(0.01))
 2     InteractionPar(Cubic{Float64}(2.0, 2.0, 3.0), ContractilePar(0.02))
 3     InteractionPar(Cubic{Float64}(3.0, 2.0, 3.0), ContractilePar(0.02))
 4     InteractionPar(Cubic{Float64}(4.0, 2.0, 3.0), ContractilePar(0.04))

=================== AggTypeIdx =====================


6500×2 Matrix{Any}:
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 ⋮  
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"

===================== AggIdx ======================


6500×2 Matrix{Any}:
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 ⋮  
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"

===================== Position ======================


6500×3 Matrix{Float64}:
  98.5   -4.62  -13.88
 100.5   -4.62  -13.88
 102.5   -4.62  -13.88
  95.5   -2.89  -13.88
  97.5   -2.89  -13.88
  99.5   -2.89  -13.88
 101.5   -2.89  -13.88
 103.5   -2.89  -13.88
  94.5   -1.15  -13.88
  96.5   -1.15  -13.88
  98.5   -1.15  -13.88
 100.5   -1.15  -13.88
 102.5   -1.15  -13.88
   ⋮            
   3.5   97.69    8.98
  -3.5   99.42    8.98
  -1.5   99.42    8.98
   0.5   99.42    8.98
   2.5   99.42    8.98
  -2.5  101.15    8.98
  -0.5  101.15    8.98
   1.5  101.15    8.98
   3.5  101.15    8.98
  -1.5  102.89    8.98
   0.5  102.89    8.98
   2.5  102.89    8.98

===================== Outline ======================


6500-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

Outer/Total = 0.4523076923076923


## Fusion Aggs

### First

In [368]:
AGG = Aggregate(
    "HEK", 
    X, 
    InteractionPar(
        Cubic(1.0,2.0,3.0), 
        ContractilePar(0.01)
    ),
    Model
)
println("=================== ONE Aggregate ===================")
display(dump(AGG))

println("================= Fusion Aggregate ==================")
FusionAGG = fusion_agg(AGG)
show_all_aggregates(FusionAGG)

using DelimitedFiles

TEXT = hcat(FusionAGG.Outline,FusionAGG.Position)

open("tetero.xyz", "w") do f
    write(f, "$(size(FusionAGG.Position, 1))\n")
    write(f, "t=$(0)\n")
    writedlm(f,TEXT, ' ')
end

=================== ONE Aggregate ===================
Aggregate
  Name: String "HEK"
  Position: Array{Float64}((2504, 3)) [-1.5 -4.62 -13.88; 0.5 -4.62 -13.88; … ; 0.5 4.62 13.88; 2.5 4.62 13.88]
  Interaction: InteractionPar
    Force: Cubic{Float64}
      μ₁: Float64 1.0
      rₘᵢₙ: Float64 2.0
      rₘₐₓ: Float64 3.0
    Contractile: ContractilePar
      fₚ: Float64 0.01
  Radius: Float64 15.270000000000001
  Outline: Array{Int64}((2504,)) [1, 1, 1, 1, 1, 1, 1, 1, 1, 1  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


nothing

================= Fusion Aggregate ==================
===================== AggType ======================


1×4 Matrix{Any}:
 1  …  InteractionPar(Cubic{Float64}(1.0, 2.0, 3.0), ContractilePar(0.01))

=================== AggTypeIdx =====================


5008×2 Matrix{Any}:
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 ⋮  
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"

===================== AggIdx ======================


5008×2 Matrix{Any}:
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 1  "HEK"
 ⋮  
 2  "HEK"
 2  "HEK"
 2  "HEK"
 2  "HEK"
 2  "HEK"
 2  "HEK"
 2  "HEK"
 2  "HEK"
 2  "HEK"
 2  "HEK"
 2  "HEK"
 2  "HEK"

===================== Position ======================


5008×3 Matrix{Float64}:
 -16.77  -4.62  -13.88
 -14.77  -4.62  -13.88
 -12.77  -4.62  -13.88
 -19.77  -2.89  -13.88
 -17.77  -2.89  -13.88
 -15.77  -2.89  -13.88
 -13.77  -2.89  -13.88
 -11.77  -2.89  -13.88
 -20.77  -1.15  -13.88
 -18.77  -1.15  -13.88
 -16.77  -1.15  -13.88
 -14.77  -1.15  -13.88
 -12.77  -1.15  -13.88
   ⋮            
  13.77   1.15   13.88
  15.77   1.15   13.88
  17.77   1.15   13.88
  19.77   1.15   13.88
  10.77   2.89   13.88
  12.77   2.89   13.88
  14.77   2.89   13.88
  16.77   2.89   13.88
  18.77   2.89   13.88
  13.77   4.62   13.88
  15.77   4.62   13.88
  17.77   4.62   13.88

===================== Outline ======================


5008-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

Outer/Total = 0.46325878594249204


### Second

In [369]:
AGG_1 = Aggregate(
    "HEK_1", 
    X, 
    InteractionPar(
        Cubic(1.0,2.0,3.0), 
        ContractilePar(0.01)
    ),
    Model
)
AGG_2 = Aggregate(
    "HEK_2", 
    Y, 
    InteractionPar(
        Cubic(1.0,2.0,3.0), 
        ContractilePar(0.01)
    ),
    Model
)

Aggregate("HEK_2", [-1.5 -2.89 -8.98; 0.5 -2.89 -8.98; … ; 0.5 2.89 8.98; 2.5 2.89 8.98], InteractionPar(Cubic{Float64}(1.0, 2.0, 3.0), ContractilePar(0.01)), 10.430000000000001, [1, 1, 1, 1, 1, 1, 1, 1, 1, 1  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [370]:
Fusion_AGG = AllAggregates(
        [AGG_1, AGG_2],
        [
            [AGG_1.Name,[-AGG_1.Radius ,0 ,0]],
            [AGG_2.Name,[ AGG_2.Radius ,0 ,0]]
        ]
    )

using DelimitedFiles

TEXT = hcat(Fusion_AGG.Outline,Fusion_AGG.Position)

open("tetero_2.xyz", "w") do f
    write(f, "$(size(Fusion_AGG.Position, 1))\n")
    write(f, "t=$(0)\n")
    writedlm(f,TEXT, ' ')
end

================= Fusion Aggregate ==================
===================== AggType ======================


2×4 Matrix{Any}:
 1  …  InteractionPar(Cubic{Float64}(1.0, 2.0, 3.0), ContractilePar(0.01))
 2     InteractionPar(Cubic{Float64}(1.0, 2.0, 3.0), ContractilePar(0.01))

=================== AggTypeIdx =====================


3250×2 Matrix{Any}:
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 ⋮  
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"

===================== AggIdx ======================


3250×2 Matrix{Any}:
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 1  "HEK_1"
 ⋮  
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"
 2  "HEK_2"

===================== Position ======================


3250×3 Matrix{Float64}:
 -16.77  -4.62  -13.88
 -14.77  -4.62  -13.88
 -12.77  -4.62  -13.88
 -19.77  -2.89  -13.88
 -17.77  -2.89  -13.88
 -15.77  -2.89  -13.88
 -13.77  -2.89  -13.88
 -11.77  -2.89  -13.88
 -20.77  -1.15  -13.88
 -18.77  -1.15  -13.88
 -16.77  -1.15  -13.88
 -14.77  -1.15  -13.88
 -12.77  -1.15  -13.88
   ⋮            
  13.93  -2.31    8.98
   6.93  -0.58    8.98
   8.93  -0.58    8.98
  10.93  -0.58    8.98
  12.93  -0.58    8.98
   7.93   1.15    8.98
   9.93   1.15    8.98
  11.93   1.15    8.98
  13.93   1.15    8.98
   8.93   2.89    8.98
  10.93   2.89    8.98
  12.93   2.89    8.98

===================== Outline ======================


3250-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

Outer/Total = 0.4523076923076923


### Third

In [ ]:
AGG_1 = Aggregate(
    "HEK_1", 
    X, 
    InteractionPar(
        Cubic(1.0,2.0,3.0), 
        ContractilePar(0.01)
    ),
    Model
)
AGG_2 = Aggregate(
    "HEK_2", 
    Y, 
    InteractionPar(
        Cubic(1.0,2.0,3.0), 
        ContractilePar(0.01)
    ),
    Model
)

In [381]:
Fusion_AGG_2 = AllAggregates(
        [AGG_1, AGG_2],
        [
            [AGG_1.Name,[0                           , 0                           ,0]],
            [AGG_2.Name,[AGG_2.Radius + AGG_1.Radius ,0                            ,0]],
            [AGG_2.Name,[0                           ,AGG_2.Radius + AGG_1.Radius  ,0]]
        ]
    )

using DelimitedFiles

TEXT = hcat(Fusion_AGG_2.Outline,Fusion_AGG_2.Position)

open("tetero_3.xyz", "w") do f
    write(f, "$(size(Fusion_AGG_2.Position, 1))\n")
    write(f, "t=$(0)\n")
    writedlm(f,TEXT, ' ')
end

# Simulation Struct