# Dependences

In [13]:
include("../../src/struct_data.jl")

MoreAgg (generic function with 2 methods)

# Force Functions

## Cubic

In [14]:
@make_struct_func Cubic
dump(Cubic)

UnionAll
  var: TypeVar
    name: Symbol T
    lb: Union{}
    ub: Any
  body: Cubic{T} <: ForceType
    μ₁::T
    rₘᵢₙ::T
    rₘₐₓ::T


In [15]:
# Parameters
μ₁   = 1.0
rₘₐₓ = 2.0
rₘᵢₙ = 3.0

3.0

In [16]:
Cubic(μ₁,rₘₐₓ,rₘᵢₙ)

Cubic{Float64}(1.0, 2.0, 3.0)

In [17]:
# Show function on specific r value
r = 1
force_func(Cubic(μ₁,rₘₐₓ,rₘᵢₙ),r)

4.0

## LennardJones

In [18]:
@make_struct_func LennardJones
dump(LennardJones)

UnionAll
  var: TypeVar
    name: Symbol T
    lb: Union{}
    ub: Any
  body: LennardJones{T} <: ForceType
    μ₁::T
    rₘᵢₙ::T
    rₘₐₓ::T


In [19]:
# Parameters
μ₁   = 1.0
rₘₐₓ = 2.0
rₘᵢₙ = 3.0

3.0

In [20]:
LennardJones(μ₁,rₘₐₓ,rₘᵢₙ)

LennardJones{Float64}(1.0, 2.0, 3.0)

In [21]:
# Show function on specific r value
r = 1.9
force_func(LennardJones(μ₁,rₘₐₓ,rₘᵢₙ),r)

1.9609746568876094

# Aggregate

## Initial Data

In [ ]:
X = Float64.(readdlm("../../data/init/Sphere/9.0.xyz")[3:end,2:end])
Y = Float64.(readdlm("../../data/init/Sphere/10.0.xyz")[3:end,2:end])

## Inizializate (Model Parameter)

In [22]:
Model = ModelPar(
    TimePar(
        t_f    = 10000.0,
        dt     = 0.5,
        n_knn  = 50,
        n_text = 100
    ),
    GeometryPar(
        outer_ratio = 0.8
    ),
    InputPar(
        path_input = "../../data/init/Sphere"
    )
)

ModelPar(TimePar(10000.0, 0.5, 50, 100), GeometryPar(0.8), InputPar("../../data/init/Sphere"))

## Simple Aggregate

In [29]:
@time AllAggs = AllAggregates(
    [Aggregate("A", X, InteractionPar(Cubic(1.0,2.0,3.0), ContractilePar(0.01)), Model)]
    ,
    [
        ["A",[100 ,0   ,0  ]],
        ["A",[0   ,100 ,0  ]]
    ]
)
show_all_aggregates(AllAggs)

  0.177828 seconds (468.73 k allocations: 27.767 MiB, 97.19% compilation time)
===================== AggType ======================


1×4 Matrix{Any}:
 1  …  InteractionPar(Cubic{Float64}(1.0, 2.0, 3.0), ContractilePar{Float64}(0.01))

=================== AggTypeIdx =====================


1076×2 Matrix{Any}:
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 ⋮  
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"

===================== AggIdx ======================


1076×2 Matrix{Any}:
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 ⋮  
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"
 2  "A"

===================== Position ======================


1076×3 Matrix{Float64}:
  98.5   -4.62  -7.35
 100.5   -4.62  -7.35
  97.5   -2.89  -7.35
  99.5   -2.89  -7.35
 101.5   -2.89  -7.35
 103.5   -2.89  -7.35
  96.5   -1.15  -7.35
  98.5   -1.15  -7.35
 100.5   -1.15  -7.35
 102.5   -1.15  -7.35
 104.5   -1.15  -7.35
  95.5    0.58  -7.35
  97.5    0.58  -7.35
   ⋮            
   3.5   99.42   7.35
  -3.5  101.15   7.35
  -1.5  101.15   7.35
   0.5  101.15   7.35
   2.5  101.15   7.35
   4.5  101.15   7.35
  -2.5  102.89   7.35
  -0.5  102.89   7.35
   1.5  102.89   7.35
   3.5  102.89   7.35
  -1.5  104.62   7.35
   0.5  104.62   7.35

===================== Outline ======================


1076-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

Outer/Total = 0.5687732342007435


## Complex Aggregate

In [28]:
@time AllAggs = AllAggregates(
    [Aggregate("A", X, InteractionPar(Cubic(1.0,2.0,3.0), ContractilePar(0.01)), Model),
     Aggregate("B", Y, InteractionPar(Cubic(2.0,2.0,3.0), ContractilePar(0.02)), Model),
     Aggregate("C", X, InteractionPar(Cubic(3.0,2.0,3.0), ContractilePar(0.02)), Model),
     Aggregate("D", Y, InteractionPar(Cubic(4.0,2.0,3.0), ContractilePar(0.04)), Model)
    ],
    [
        ["A",[100 ,0   ,0  ]],
        ["C",[0   ,100 ,0  ]],
        ["D",[0   ,0   ,100]],
        ["B",[0   ,100 ,0  ]]
    ]
)
show_all_aggregates(AllAggs)

  0.006418 seconds (49.14 k allocations: 3.486 MiB)
===================== AggType ======================


4×4 Matrix{Any}:
 1  …  InteractionPar(Cubic{Float64}(1.0, 2.0, 3.0), ContractilePar{Float64}(0.01))
 2     InteractionPar(Cubic{Float64}(2.0, 2.0, 3.0), ContractilePar{Float64}(0.02))
 3     InteractionPar(Cubic{Float64}(3.0, 2.0, 3.0), ContractilePar{Float64}(0.02))
 4     InteractionPar(Cubic{Float64}(4.0, 2.0, 3.0), ContractilePar{Float64}(0.04))

=================== AggTypeIdx =====================


2568×2 Matrix{Any}:
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 ⋮  
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"
 2  "B"

===================== AggIdx ======================


2568×2 Matrix{Any}:
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 1  "A"
 ⋮  
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"
 4  "B"

===================== Position ======================


2568×3 Matrix{Float64}:
  98.5   -4.62  -7.35
 100.5   -4.62  -7.35
  97.5   -2.89  -7.35
  99.5   -2.89  -7.35
 101.5   -2.89  -7.35
 103.5   -2.89  -7.35
  96.5   -1.15  -7.35
  98.5   -1.15  -7.35
 100.5   -1.15  -7.35
 102.5   -1.15  -7.35
 104.5   -1.15  -7.35
  95.5    0.58  -7.35
  97.5    0.58  -7.35
   ⋮            
   3.5   97.69   8.98
  -3.5   99.42   8.98
  -1.5   99.42   8.98
   0.5   99.42   8.98
   2.5   99.42   8.98
  -2.5  101.15   8.98
  -0.5  101.15   8.98
   1.5  101.15   8.98
   3.5  101.15   8.98
  -1.5  102.89   8.98
   0.5  102.89   8.98
   2.5  102.89   8.98

===================== Outline ======================


2568-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

Outer/Total = 0.5311526479750779
