# Dependences

In [1]:
include("../../src/struct_data.jl")
include("../../src/neighbor.jl")
include("../../src/forces/forces.jl")

cu_force

# Model

In [2]:
@time Model = ModelSet(
    TimeModel(
        tₛᵢₘ  = 10000.0,
        dt    = 0.5,
        nₖₙₙ  = 50,
        nₛₐᵥₑ = 100
    ),
    InputModel(
        outer_ratio = 0.8,
        path_input = "../../data/init/Sphere"
    )
)
dump(Model)

  0.000001 seconds (3 allocations: 112 bytes)
ModelSet
  Time: TimeModel
    tₛᵢₘ: Float64 10000.0
    dt: Float64 0.5
    nₖₙₙ: Int64 50
    nₛₐᵥₑ: Int64 100
  Input: InputModel
    outer_ratio: Float64 0.8
    path_input: String "../../data/init/Sphere"


# Aggregate

In [3]:
FusionAGG = nothing
# @time @start_agg FusionAGG = FusionAggregate(
@time FusionAGG = FusionAggregate(
    [
        AggType(
            "HEK_1", 
            InteractionPar(
                Cubic(0.01,2.0,3.0), 
                ContractilePar(0.001)
            ),
            Float64.(readdlm("../../data/init/Sphere/15.0.xyz")[3:end,2:end]) |> cu
        ),
        AggType(
            "HEK_2", 
            InteractionPar(
                Cubic(0.01,2.0,3.0), 
                ContractilePar(0.001)
            ),
            Float64.(readdlm("../../data/init/Sphere/15.0.xyz")[3:end,2:end]) |> cu
        )
    ], 
    Model
)
show_aggregates(FusionAGG)

  8.946409 seconds (13.11 M allocations: 1.133 GiB, 3.59% gc time, 5.04% compilation time)
========================= Type =======================


2-element Vector{AggType}:
 AggType("HEK_1", InteractionPar(Cubic{Float64}(0.01, 2.0, 3.0), ContractilePar(0.001)), 15.27f0, Float32[-1.5 -4.62 -13.88; 0.5 -4.62 -13.88; … ; 0.5 4.62 13.88; 2.5 4.62 13.88], CuArray{Float32, 2, CUDA.Mem.DeviceBuffer})
 AggType("HEK_2", InteractionPar(Cubic{Float64}(0.01, 2.0, 3.0), ContractilePar(0.001)), 15.27f0, Float32[-1.5 -4.62 -13.88; 0.5 -4.62 -13.88; … ; 0.5 4.62 13.88; 2.5 4.62 13.88], CuArray{Float32, 2, CUDA.Mem.DeviceBuffer})

======================   Index =======================
Index of List of Aggregates


1×5008 CuArray{Int64, 2, CUDA.Mem.DeviceBuffer}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  2  2  2  2  2  2  2  2  2  2  2  2

Index of Number of Aggregates


1×5008 CuArray{Int64, 2, CUDA.Mem.DeviceBuffer}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  2  2  2  2  2  2  2  2  2  2  2  2

Index of Name of Aggregates


1×5008 Matrix{String}:
 "HEK_1"  "HEK_1"  "HEK_1"  "HEK_1"  …  "HEK_2"  "HEK_2"  "HEK_2"  "HEK_2"

====================== Position =====================


5008×3 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
 -16.77  -4.62  -13.88
 -14.77  -4.62  -13.88
 -12.77  -4.62  -13.88
 -19.77  -2.89  -13.88
 -17.77  -2.89  -13.88
 -15.77  -2.89  -13.88
 -13.77  -2.89  -13.88
 -11.77  -2.89  -13.88
 -20.77  -1.15  -13.88
 -18.77  -1.15  -13.88
 -16.77  -1.15  -13.88
 -14.77  -1.15  -13.88
 -12.77  -1.15  -13.88
   ⋮            
  13.77   1.15   13.88
  15.77   1.15   13.88
  17.77   1.15   13.88
  19.77   1.15   13.88
  10.77   2.89   13.88
  12.77   2.89   13.88
  14.77   2.89   13.88
  16.77   2.89   13.88
  18.77   2.89   13.88
  13.77   4.62   13.88
  15.77   4.62   13.88
  17.77   4.62   13.88

======================== Geometry ===================
Radius_agg


1×5008 Matrix{Float32}:
 15.27  15.27  15.27  15.27  15.27  …  15.27  15.27  15.27  15.27  15.27

Outline


1×5008 Matrix{Int64}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1

Outer/Total = 0.46325878594249204
====================== Simulation ===================
---------------------- Parameter --------------------
Force


Cubic{CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}(Float32[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01  …  0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01], Float32[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0  …  2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0], Float32[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0  …  3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0])

Contractile


ContractilePar(Float32[0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001  …  0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001])

Radius


2-element CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}:
 15.27
 15.27

------------------ Neighbors Size -------------------
idx      = (5008, 5008)
idx_red  = (21, 5008)
idx_sum  = (1, 5008)
idx_cont = (50, 5008)
------------------- Forces Size ---------------------
dX       = (5008, 3)
F        = (5008, 3)


# kNN

In [4]:
println("------------------------ SIZE ------------------------")
println("r_max         = $(FusionAGG.Type[1].Interaction.Force.rₘₐₓ)")
println("Size X        = $(size(FusionAGG.Position))")
println("Size idx      = $(size(FusionAGG.Simulation.Neighbor.idx))")
println("Size idx_real  = $(size(FusionAGG.Simulation.Neighbor.idx))")
println("Size idx_sum   = $(size(FusionAGG.Simulation.Neighbor.idx_sum))")
println("Size idx_red   = $(size(FusionAGG.Simulation.Neighbor.idx_red))")
@time nearest_neighbors(FusionAGG)
println("------------------------ IDX -------------------------")
println("idx")
display(FusionAGG.Simulation.Neighbor.idx)
println("idx_red")
display(FusionAGG.Simulation.Neighbor.idx_red)
println("idx_sum")
display(FusionAGG.Simulation.Neighbor.idx_sum)
println("idx_cont")
display(FusionAGG.Simulation.Neighbor.idx_cont)

------------------------ SIZE ------------------------
r_max         = 3.0
Size X        = (5008, 3)
Size idx      = (5008, 5008)
Size idx_real  = (5008, 5008)
Size idx_sum   = (1, 5008)
Size idx_red   = (21, 5008)
Threads = (32, 32) | Blocks  = (157, 157)
Threads = 256 | Blocks  = 20
Threads = (32, 32) | Blocks  = (157, 157)
 24.542925 seconds (31.21 M allocations: 1.773 GiB, 2.92% gc time, 16.18% compilation time)
------------------------ IDX -------------------------
idx


5008×5008 CuArray{Int64, 2, CUDA.Mem.DeviceBuffer}:
 1  1  0   0   1   1   0   0   0   0  …     0     0     0     0     0     0
 2  2  2   0   0   2   2   0   0   0        0     0     0     0     0     0
 0  3  3   0   0   0   3   3   0   0        0     0     0     0     0     0
 0  0  0   4   4   0   0   0   4   4        0     0     0     0     0     0
 5  0  0   5   5   5   0   0   0   5        0     0     0     0     0     0
 6  6  0   0   6   6   6   0   0   0  …     0     0     0     0     0     0
 0  7  7   0   0   7   7   7   0   0        0     0     0     0     0     0
 0  0  8   0   0   0   8   8   0   0        0     0     0     0     0     0
 0  0  0   9   0   0   0   0   9   9        0     0     0     0     0     0
 0  0  0  10  10   0   0   0  10  10        0     0     0     0     0     0
 0  0  0   0  11  11   0   0   0  11  …     0     0     0     0     0     0
 0  0  0   0   0  12  12   0   0   0        0     0     0     0     0     0
 0  0  0   0   0   0  13  13   0   0

idx_red


21×5008 CuArray{Int64, 2, CUDA.Mem.DeviceBuffer}:
  1   1   2   4   1   1   2   3   4  …  4949  4950  4951  4957  4958  4959
  2   2   3   5   4   2   3   7   9     4957  4958  4959  4964  4965  4966
  5   3   7   9   5   5   6   8  10     4958  4959  4960  4965  4966  4967
  6   6   8  10   6   6   7  13  15     4964  4965  4966  4971  4972  4973
 35   7  37  40  10   7   8  14  48     4965  4966  4967  4972  4973  4974
 36  36  38  41  11  11  12  44  49  …  4966  4967  4968  4973  4974  4975
 37  37  39  42  41  12  13  45  50     4997  4998  4999  5002  5003  5004
 42  38  44  49  42  42  43  46  57     4998  4999  5000  5003  5004  5005
 43  43  45  50  43  43  44  53  58     5002  5003  5004  5006  5006  5007
 51  44  53  58  50  44  45  54  66     5003  5004  5005  5007  5007  5008
  0  52   0   0  51  51  52  62   0  …  5004  5005  5008     0  5008     0
  0   0   0   0  59  52  53   0   0     5006  5007     0     0     0     0
  0   0   0   0   0  60  61   0   0     5007  5008

idx_sum


1×5008 CuArray{Int64, 2, CUDA.Mem.DeviceBuffer}:
 10  11  10  10  12  13  13  11  10  …  11  10  12  13  13  11  10  11  10

idx_cont


50×5008 CuArray{Int64, 2, CUDA.Mem.DeviceBuffer}:
 51  52  39  58  10  42   6   8  48  …  4966  4959  4967  4971  4966  4967
 42  43  38   9  59  43   6  13  50     5002  4967  4959  4957  5008  4967
  5   1   8   9   4  43   3  62  50     4964  5004  4966  4971  5003  5007
 35  38   3   4  11  11  52  14  50     4998  5004  4967  5007  5006  5007
 36   3  53   5   4   1  61   3   9     4997  4965  4951  4964  4972  4973
 37   6  53  58  10  11   3   3  48  …  4965  5003  5004  5007  5003  4967
 37  37   8   5  59  60  44   8  66     4957  4950  4999  5006  4966  5004
 42  38  39  49  10  52   8   8  66     4964  4950  4959  4971  4965  5008
 42   2   7  58  42  43   7   8  49     5002  5008  4960  5006  4958  4959
  5   6  45   5  42  51  44  45  48     4965  4967  4959  5007  4965  5008
  1   2   8  41   6   2  45  46   4  …  4997  4959  4959  5007  5008  4975
  1  44  45   5   4  44  12  62  50     4966  4966  4967  4972  5003  5004
 42   6   8  49  42   1   6  53  58     4998  5008

# Force

## GPU

In [5]:
println("Force Parameter")
display(FusionAGG.Simulation.Parameter.Force)
println("Contractile Parameter")
display(FusionAGG.Simulation.Parameter.Contractile.fₚ')
println("Running CUDA kernel")
@time cu_force(FusionAGG,1.0)
println("Force")
display(FusionAGG.Simulation.Force.F)

Force Parameter


Cubic{CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}(Float32[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01  …  0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01], Float32[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0  …  2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0], Float32[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0  …  3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0])

Contractile Parameter


1×5008 adjoint(::CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}) with eltype Float32:
 0.001  0.001  0.001  0.001  0.001  …  0.001  0.001  0.001  0.001  0.001

Running CUDA kernel
  2.028967 seconds (2.96 M allocations: 169.473 MiB, 4.52% gc time, 32.44% compilation time)
Force


5008×3 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
  0.0          -0.000831988  -0.00021189
  0.0          -0.000831988  -0.00021189
 -0.000708019   0.000392189  -0.000212381
  0.0          -0.000683325  -0.00021189
  0.000489364  -0.000717842   0.000364654
  0.000708019   0.000571713  -0.000212382
  0.001         0.000164602   0.000364654
  8.91939f-6    0.000149172   0.000364654
  0.000731929   0.000325632  -0.000211375
 -0.000500444  -0.00102452    0.000364828
  0.001        -0.000158756   0.000364828
 -0.000706996   0.000251302  -0.000211375
  0.0           0.000421063  -0.000449918
  ⋮                          
 -0.000500444   0.00102452   -0.000364828
  0.000498284  -0.000708258  -0.000364828
  0.001         0.000158756  -0.000364828
 -0.000534993   0.000385505   0.000452033
 -0.001        -0.000133741  -0.000364654
  0.000489364   0.000717842  -0.000364654
 -0.000708019  -0.000571713   0.000212382
 -0.000500419   0.000125641   0.00045103
  8.91939f-6   -0.000725658   0.000452453

## CPU

In [6]:
X_CPU          = Matrix(FusionAGG.Position)
idx_red_CPU    = Matrix(FusionAGG.Simulation.Neighbor.idx_red)
idx_cont_CPU   = Matrix(FusionAGG.Simulation.Neighbor.idx_cont)
force_CPU      = zeros(size(X_CPU))

Param = vcat(
        [
            unique(
                getfield(FusionAGG.Simulation.Parameter.Force, fieldnames(Cubic)[i])
            ) for i=1:size(fieldnames(Cubic),1)
    ]...)
Param          = Cubic(Param...)
A_con          = unique(FusionAGG.Simulation.Parameter.Contractile.fₚ)[1]

t_knn = 1

┌ Warning: Performing scalar indexing on task Task (runnable) @0x00007f4c9d5624d0.
│ Invocation of getindex resulted in scalar indexing of a GPU array.
│ This is typically caused by calling an iterating implementation of a method.
│ Such implementations *do not* execute on the GPU, but very slowly on the CPU,
│ and therefore are only permitted from the REPL for prototyping purposes.
│ If you did intend to index this array, annotate the caller with @allowscalar.
└ @ GPUArraysCore ~/.julia/packages/GPUArraysCore/HaQcr/src/GPUArraysCore.jl:106


1

In [7]:
function runCPU()
    for j = 1:size(idx_red_CPU,1)
        for i =1:size(X_CPU,1)
            if idx_red_CPU[j,i] != 0 && idx_red_CPU[j,i] != i
                dist = euclidean(X_CPU,i,idx_red_CPU[j,i])
                force_CPU[i,:] += force_func(Param,dist) .* (X_CPU[i,:] - X_CPU[idx_red_CPU[j,i],:]) ./ dist
            end
        end
    end

    for i =1:size(X_CPU,1)
        if idx_cont_CPU[t_knn,i] != i
            dist = euclidean(X_CPU,i,idx_cont_CPU[t_knn,i])
            force_CPU[i,:] += A_con .* (X_CPU[i,:] - X_CPU[idx_cont_CPU[t_knn,i],:]) ./ dist
        end
    end
end

runCPU()
display(force_CPU)

5008×3 Matrix{Float64}:
  0.0          -0.000831988  -0.00021189
  0.0          -0.000831988  -0.00021189
 -0.000708019   0.000392189  -0.000212381
  0.0          -0.000683325  -0.00021189
  0.000489364  -0.000717842   0.000364654
  0.000708019   0.000571713  -0.000212382
  0.001         0.000164602   0.000364654
  8.91939e-6    0.000149172   0.000364654
  0.00073193    0.00032563   -0.000211373
 -0.000500444  -0.00102453    0.000364829
  0.001        -0.000158757   0.000364829
 -0.000706996   0.0002513    -0.000211373
  0.0           0.000421061  -0.000449916
  ⋮                          
 -0.000500444   0.00102453   -0.000364829
  0.000498284  -0.000708257  -0.000364829
  0.001         0.000158757  -0.000364829
 -0.000534993   0.000385507   0.000452031
 -0.001        -0.000133741  -0.000364654
  0.000489364   0.000717842  -0.000364654
 -0.000708019  -0.000571713   0.000212382
 -0.000500419   0.000125641   0.00045103
  8.91939e-6   -0.000725658   0.000452453
  0.000708019  -0.00039218

## GPU vs CPU

In [8]:
using Test
@test Matrix(FusionAGG.Simulation.Force.F) ≈ force_CPU atol=0.01

Test Passed