# Dependences

In [1]:
include("../../src/struct_data.jl")
include("../../src/neighbor.jl")
include("../../src/forces/forces.jl")

sum_force!

# Model

In [2]:
@time model = ModelSet(
    TimeModel(
        tₛᵢₘ  = 150000.0,
        dt    = 0.5,
        nₖₙₙ  = 100,
        nₛₐᵥₑ = 50
    ),
    InputModel(
        outer_ratio = 0.8,
        path_input  = "../../data/init/Sphere"
    ),
    OutputModel(
        name_output = "Test_1",
        path_output = ""
    ) 
)

dump(model)

  0.000013 seconds (5 allocations: 208 bytes)
ModelSet
  Time: TimeModel
    tₛᵢₘ: Float64 150000.0
    dt: Float64 0.5
    nₖₙₙ: Int64 100
    nₛₐᵥₑ: Int64 50
  Input: InputModel
    outer_ratio: Float64 0.8
    path_input: String "../../data/init/Sphere"
  Output: OutputModel
    name_output: String "Test_1"
    path_output: String ""


# Aggregate

In [3]:
agg = nothing
# @time @start_agg FusionAGG = FusionAggregate(
@time agg = FusionAggregate(
    [
        AggType(
            "HEK_1", 
            InteractionPar(
                Cubic(0.01,2.0,3.0), 
                ContractilePar(0.001)
            ),
            Float64.(readdlm("../../data/init/Sphere/15.0.xyz")[3:end,2:end]) |> cu
        ),
        AggType(
            "HEK_2", 
            InteractionPar(
                Cubic(0.01,2.0,3.0), 
                ContractilePar(0.001)
            ),
            Float64.(readdlm("../../data/init/Sphere/15.0.xyz")[3:end,2:end]) |> cu
        )
    ], 
    model
)
show_aggregates(agg)

  8.427463 seconds (7.62 M allocations: 837.354 MiB, 4.54% gc time)
========================= Type =======================


2-element Vector{AggType}:
 AggType("HEK_1", InteractionPar(Cubic{Float64}(0.01, 2.0, 3.0), ContractilePar(0.001)), 15.27f0, Float32[-1.5 -4.62 -13.88; 0.5 -4.62 -13.88; … ; 0.5 4.62 13.88; 2.5 4.62 13.88], CuArray{Float32, 2, CUDA.Mem.DeviceBuffer})
 AggType("HEK_2", InteractionPar(Cubic{Float64}(0.01, 2.0, 3.0), ContractilePar(0.001)), 15.27f0, Float32[-1.5 -4.62 -13.88; 0.5 -4.62 -13.88; … ; 0.5 4.62 13.88; 2.5 4.62 13.88], CuArray{Float32, 2, CUDA.Mem.DeviceBuffer})

======================   Index =======================
Index of List of Aggregates


1×5008 CuArray{Int64, 2, CUDA.Mem.DeviceBuffer}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  2  2  2  2  2  2  2  2  2  2  2  2

Index of Number of Aggregates


1×5008 CuArray{Int64, 2, CUDA.Mem.DeviceBuffer}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  2  2  2  2  2  2  2  2  2  2  2  2

Index of Name of Aggregates


1×5008 Matrix{String}:
 "HEK_1"  "HEK_1"  "HEK_1"  "HEK_1"  …  "HEK_2"  "HEK_2"  "HEK_2"  "HEK_2"

====================== Position =====================


5008×3 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
 -16.77  -4.62  -13.88
 -14.77  -4.62  -13.88
 -12.77  -4.62  -13.88
 -19.77  -2.89  -13.88
 -17.77  -2.89  -13.88
 -15.77  -2.89  -13.88
 -13.77  -2.89  -13.88
 -11.77  -2.89  -13.88
 -20.77  -1.15  -13.88
 -18.77  -1.15  -13.88
 -16.77  -1.15  -13.88
 -14.77  -1.15  -13.88
 -12.77  -1.15  -13.88
   ⋮            
  13.77   1.15   13.88
  15.77   1.15   13.88
  17.77   1.15   13.88
  19.77   1.15   13.88
  10.77   2.89   13.88
  12.77   2.89   13.88
  14.77   2.89   13.88
  16.77   2.89   13.88
  18.77   2.89   13.88
  13.77   4.62   13.88
  15.77   4.62   13.88
  17.77   4.62   13.88

======================== Geometry ===================
Radius_agg


1×5008 Matrix{Float32}:
 15.27  15.27  15.27  15.27  15.27  …  15.27  15.27  15.27  15.27  15.27

Outline


1×5008 Matrix{Int64}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1

Outer/Total = 1.536741214057508
====================== Simulation ===================
---------------------- Parameter --------------------
Force


Cubic{CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}(Float32[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01  …  0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01], Float32[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0  …  2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0], Float32[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0  …  3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0])

Contractile


ContractilePar(Float32[0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001  …  0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001])

Radius


2-element CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}:
 15.27
 15.27

------------------ Neighbors Size -------------------
idx      = (5008, 5008)
idx_red  = (1000, 5008)
idx_sum  = (1, 5008)
idx_cont = (100, 5008)
------------------- Forces Size ---------------------
dX       = (5008, 3)
F        = (5008, 3)


# kNN

In [4]:
dist = zeros(size(agg.Simulation.Neighbor.idx_red)) |> cu

println("------------------------ SIZE ------------------------")
threads=(100)
@cuda(
    threads=threads,
    blocks=cld.(size(agg.Position,1),threads),
    dist_kernel!(
        agg.Simulation.Neighbor.idx_red,
        agg.Simulation.Neighbor.idx_cont,
        agg.Simulation.Neighbor.idx_sum,
        dist,
        agg.Position,
        agg.Simulation.Parameter.Force.rₘₐₓ
    )
)   

println("------------------------ IDX -------------------------")
display(agg.Simulation.Neighbor.idx_red)

------------------------ SIZE ------------------------
------------------------ IDX -------------------------


1000×5008 CuArray{Int32, 2, CUDA.Mem.DeviceBuffer}:
 36  37  38  41  42  43  44  45  57  …  4965  4966  4967  4972  4973  4974
  6   7   8  49   1   2   3   3  58     5006  5007  5008  5002  5003  5004
  5   6   7  50  50   1   2  53  15     5007  5008  4959  5003  5004  5005
 42  43  44   5  51  51  52  54  10     4958  4959  4960  4965  4966  4967
 43  44  45  10   6  52  53   7  49     4957  4958  5004  4964  4965  4966
  2   3   2   9   4   7   8  14   4  …  5002  5003  4999  5007  5006  5007
 35   1  37  40  11   5   6  13  66     5004  5005  5000  4973  5008  4975
 37  36  39  42  10  12  13  44  50     4997  4998  4966  4971  4972  4973
 51  38  53  58  41  11  12  46  48     4998  4999  4968  4957  4974  4959
  0  52   0   0  43  42  43  62   0     4964  4965  4951     0  4958     0
  0   0   0   0  59  44  45   0   0  …  4966  4967     0     0     0     0
  0   0   0   0   0  60  61   0   0     4949  4950     0     0     0     0
  0   0   0   0   0   0   0   0   0        0    

# Force

## Function

In [5]:
dot_product(a,b,i,j) = a[i,1]*b[j,1] + a[i,2]*b[j,2] + a[i,3]*b[j,3] 

dot_product (generic function with 1 method)

In [6]:
points       = copy(agg.Position)

idx_sum = agg.Simulation.Neighbor.idx_sum
idx     = agg.Simulation.Neighbor.idx_red
pol     = agg.Simulation.Force.Pol

force   = agg.Simulation.Force.F

function teso!(points,force,pol,idx_sum,idx)

    i = (blockIdx().x - 1) * blockDim().x + threadIdx().x
    k = (blockIdx().y - 1) * blockDim().y + threadIdx().y

    shared = @cuStaticSharedMem(Float32, (size(points,1),3))

    if i <= size(points, 1) && k <= size(points, 2)

        # Cleaning force
        force[i,k] = 0

        # # Generating Polarization vector
        phi = 2*pi*(2*rand() - 1)

        pol[i,3] = 2*rand() - 1
        pol[i,1] = sqrt(1-pol[i,3]^2)*cos(phi)
        pol[i,2] = sqrt(1-pol[i,3]^2)*sin(phi)

        for j=1:idx_sum[i]
            dist = euclidean(points,idx[j,i],i)
            shared[i,k] = (points[i,k]-points[idx[j,i],k])/dist

            # N_j = 

            force[i,k] = dist
        end
    end

    return nothing

end

threads=(16,3)
@cuda(
    threads=threads,
    blocks=(cld.(size(points,1)+1,threads[1]),1),
    teso!(points,force,pol,idx_sum,idx)
)
force

LoadError: InvalidIRError: compiling MethodInstance for teso!(::CuDeviceMatrix{Float32, 1}, ::CuDeviceMatrix{Float32, 1}, ::CuDeviceMatrix{Float32, 1}, ::CuDeviceMatrix{Int32, 1}, ::CuDeviceMatrix{Int32, 1}) resulted in invalid LLVM IR
Reason: unsupported call to an unknown function (call to jl_f_apply_type)
Stacktrace:
 [1] Val
   @ ./essentials.jl:801
 [2] CuStaticSharedArray
   @ ~/.julia/packages/CUDA/pCcGc/src/device/intrinsics/memory_shared.jl:18
 [3] macro expansion
   @ ~/.julia/packages/CUDA/pCcGc/src/device/intrinsics/memory_shared.jl:26
 [4] teso!
   @ ./In[6]:14
Reason: unsupported call to an unknown function (call to ijl_new_structv)
Stacktrace:
 [1] Val
   @ ./essentials.jl:799
 [2] Val
   @ ./essentials.jl:801
 [3] CuStaticSharedArray
   @ ~/.julia/packages/CUDA/pCcGc/src/device/intrinsics/memory_shared.jl:18
 [4] macro expansion
   @ ~/.julia/packages/CUDA/pCcGc/src/device/intrinsics/memory_shared.jl:26
 [5] teso!
   @ ./In[6]:14
Reason: unsupported dynamic function invocation (call to emit_shmem)
Stacktrace:
 [1] CuStaticSharedArray
   @ ~/.julia/packages/CUDA/pCcGc/src/device/intrinsics/memory_shared.jl:18
 [2] macro expansion
   @ ~/.julia/packages/CUDA/pCcGc/src/device/intrinsics/memory_shared.jl:26
 [3] teso!
   @ ./In[6]:14
Reason: unsupported dynamic function invocation (call to CuDeviceMatrix{Float32, 3})
Stacktrace:
 [1] CuStaticSharedArray
   @ ~/.julia/packages/CUDA/pCcGc/src/device/intrinsics/memory_shared.jl:19
 [2] macro expansion
   @ ~/.julia/packages/CUDA/pCcGc/src/device/intrinsics/memory_shared.jl:26
 [3] teso!
   @ ./In[6]:14
Hint: catch this exception as `err` and call `code_typed(err; interactive = true)` to introspect the erronous code with Cthulhu.jl

In [ ]:
# function test!(idx,idx_cont,idx_sum,points,force,force_par,cont_par,dt,t_knn,pol_mat)
#     # pol_mat
#     # Defining Index for kernel
#     i = (blockIdx().x - 1) * blockDim().x + threadIdx().x
#     k = (blockIdx().y - 1) * blockDim().y + threadIdx().y

#     # Limiting data inside matrix
#     if i <= size(points, 1) && k <= size(points, 2)

#         # Cleaning force
#         force[i,k] = 0

#         # # Generating Polarization vector
#         phi = 2*pi*(2*rand() - 1)

#         pol_mat[i,3] = 2*rand() - 1
#         pol_mat[i,1] = sqrt(1-pol_mat[i,3]^2)*cos(phi)
#         pol_mat[i,2] = sqrt(1-pol_mat[i,3]^2)*sin(phi)

#         # Iterate on each row
#         # for j=1:size(idx,1)
#         for j=1:idx_sum[i]
#             # Finding forces
#             if idx[j,i] != 0
#                 dist = euclidean(points,idx[j,i],i)
#                 # if dist < force_par.rₘₐₓ[i]
#                 force[i,k] += force_func(force_par,i,dist) * (points[i,k]-points[idx[j,i],k])/dist
#                 # end

#             end
#         end

#         points[i,k] = points[i,k] + force[i,k] * dt
        
#     end
#     return nothing
# end

## GPU

In [ ]:
# threads=(16,3)
# @cuda(
#     threads=threads,
#     blocks=(cld.(size(agg.Position,1)+1,threads[1]),1),
#     sum_force!(agg.Simulation.Neighbor.idx_red,agg.Simulation.Neighbor.idx_cont,agg.Simulation.Neighbor.idx_sum,agg.Position,agg.Simulation.Force.F,agg.Simulation.Parameter.Force,agg.Simulation.Parameter.Contractile.fₚ,model.Time.dt,1,agg.Simulation.Force.Pol)
# )
# display(agg.Simulation.Force.Pol)
# display(agg.Position)

## CPU

In [ ]:
# X_CPU          = Matrix(FusionAGG.Position)
# idx_red_CPU    = Matrix(FusionAGG.Simulation.Neighbor.idx_red)
# idx_cont_CPU   = Matrix(FusionAGG.Simulation.Neighbor.idx_cont)
# force_CPU      = zeros(size(X_CPU))

# Param = vcat(
#         [
#             unique(
#                 getfield(FusionAGG.Simulation.Parameter.Force, fieldnames(Cubic)[i])
#             ) for i=1:size(fieldnames(Cubic),1)
#     ]...)
# Param          = Cubic(Param...)
# A_con          = unique(FusionAGG.Simulation.Parameter.Contractile.fₚ)[1]

# t_knn = 1

In [ ]:
# function runCPU()
#     for j = 1:size(idx_red_CPU,1)
#         for i =1:size(X_CPU,1)
#             if idx_red_CPU[j,i] != 0 && idx_red_CPU[j,i] != i
#                 dist = euclidean(X_CPU,i,idx_red_CPU[j,i])
#                 force_CPU[i,:] += force_func(Param,dist) .* (X_CPU[i,:] - X_CPU[idx_red_CPU[j,i],:]) ./ dist
#             end
#         end
#     end

#     for i =1:size(X_CPU,1)
#         if idx_cont_CPU[t_knn,i] != i
#             dist = euclidean(X_CPU,i,idx_cont_CPU[t_knn,i])
#             force_CPU[i,:] += A_con .* (X_CPU[i,:] - X_CPU[idx_cont_CPU[t_knn,i],:]) ./ dist
#         end
#     end
# end

# runCPU()
# display(force_CPU)

## GPU vs CPU

In [ ]:
# using Test
# @test Matrix(FusionAGG.Simulation.Force.F) ≈ force_CPU atol=0.01