# Dependences

In [32]:
include("../../src/struct_data.jl")
include("../../src/neighbor.jl")
include("../../src/forces/forces.jl")

sum_force!

# Model

In [33]:
@time model = ModelSet(
    TimeModel(
        tₛᵢₘ  = 150000.0,
        dt    = 0.5,
        nₖₙₙ  = 100,
        nₛₐᵥₑ = 50
    ),
    InputModel(
        outer_ratio = 0.8,
        path_input  = "../../data/init/Sphere"
    ),
    OutputModel(
        name_output = "Test_1",
        path_output = ""
    ) 
)

dump(model)

  0.000001 seconds (4 allocations: 144 bytes)
ModelSet
  Time: TimeModel
    tₛᵢₘ: Float64 150000.0
    dt: Float64 0.5
    nₖₙₙ: Int64 100
    nₛₐᵥₑ: Int64 50
  Input: InputModel
    outer_ratio: Float64 0.8
    path_input: String "../../data/init/Sphere"
  Output: OutputModel
    name_output: String "Test_1"
    path_output: String ""


# Aggregate

In [34]:
agg = nothing
# @time @start_agg FusionAGG = FusionAggregate(
@time agg = FusionAggregate(
    [
        AggType(
            "HEK_1", 
            InteractionPar(
                Cubic(0.01,2.0,3.0), 
                ContractilePar(0.001)
            ),
            Float64.(readdlm("../../data/init/Sphere/15.0.xyz")[3:end,2:end]) |> cu
        ),
        AggType(
            "HEK_2", 
            InteractionPar(
                Cubic(0.01,2.0,3.0), 
                ContractilePar(0.001)
            ),
            Float64.(readdlm("../../data/init/Sphere/15.0.xyz")[3:end,2:end]) |> cu
        )
    ], 
    model
)
show_aggregates(agg)

2-element Vector{AggType}:
 AggType("HEK_1", InteractionPar(Cubic{Float64}(0.01, 2.0, 3.0), ContractilePar(0.001)), 15.27f0, Float32[-1.5 -4.62 -13.88; 0.5 -4.62 -13.88; … ; 0.5 4.62 13.88; 2.5 4.62 13.88], CuArray{Float32, 2, CUDA.Mem.DeviceBuffer})
 AggType("HEK_2", InteractionPar(Cubic{Float64}(0.01, 2.0, 3.0), ContractilePar(0.001)), 15.27f0, Float32[-1.5 -4.62 -13.88; 0.5 -4.62 -13.88; … ; 0.5 4.62 13.88; 2.5 4.62 13.88], CuArray{Float32, 2, CUDA.Mem.DeviceBuffer})

1×5008 CuArray{Int64, 2, CUDA.Mem.DeviceBuffer}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  2  2  2  2  2  2  2  2  2  2  2  2

1×5008 CuArray{Int64, 2, CUDA.Mem.DeviceBuffer}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  2  2  2  2  2  2  2  2  2  2  2  2

1×5008 Matrix{String}:
 "HEK_1"  "HEK_1"  "HEK_1"  "HEK_1"  …  "HEK_2"  "HEK_2"  "HEK_2"  "HEK_2"

5008×3 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
 -16.77  -4.62  -13.88
 -14.77  -4.62  -13.88
 -12.77  -4.62  -13.88
 -19.77  -2.89  -13.88
 -17.77  -2.89  -13.88
 -15.77  -2.89  -13.88
 -13.77  -2.89  -13.88
 -11.77  -2.89  -13.88
 -20.77  -1.15  -13.88
 -18.77  -1.15  -13.88
   ⋮            
  19.77   1.15   13.88
  10.77   2.89   13.88
  12.77   2.89   13.88
  14.77   2.89   13.88
  16.77   2.89   13.88
  18.77   2.89   13.88
  13.77   4.62   13.88
  15.77   4.62   13.88
  17.77   4.62   13.88

1×5008 Matrix{Float32}:
 15.27  15.27  15.27  15.27  15.27  …  15.27  15.27  15.27  15.27  15.27

1×5008 Matrix{Int64}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1

Cubic{CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}(Float32[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01  …  0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01], Float32[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0  …  2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0], Float32[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0  …  3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0])

ContractilePar(Float32[0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001  …  0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001])

2-element CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}:
 15.27
 15.27

  0.957715 seconds (1.99 M allocations: 465.399 MiB, 11.41% gc time)
========================= Type =======================
======================   Index =======================
Index of List of Aggregates
Index of Number of Aggregates
Index of Name of Aggregates
====================== Position =====================
======================== Geometry ===================
Radius_agg
Outline
Outer/Total = 1.536741214057508
====================== Simulation ===================
---------------------- Parameter --------------------
Force
Contractile
Radius
------------------ Neighbors Size -------------------
idx      = (5008, 5008)
idx_red  = (1000, 5008)
idx_sum  = (1, 5008)
idx_cont = (100, 5008)
------------------- Forces Size ---------------------
dX       = (5008, 3)
F        = (5008, 3)


# kNN

In [35]:
dist = zeros(size(agg.Simulation.Neighbor.idx_red)) |> cu

println("------------------------ SIZE ------------------------")
threads=(100)
@cuda(
    threads=threads,
    blocks=cld.(size(agg.Position,1),threads),
    dist_kernel!(
        agg.Simulation.Neighbor.idx_red,
        agg.Simulation.Neighbor.idx_cont,
        agg.Simulation.Neighbor.idx_sum,
        dist,
        agg.Position,
        agg.Simulation.Parameter.Force.rₘₐₓ
    )
)   

println("------------------------ IDX -------------------------")
display(agg.Simulation.Neighbor.idx_red)

------------------------ SIZE ------------------------


1000×5008 CuArray{Int32, 2, CUDA.Mem.DeviceBuffer}:
 36  37  38  41  42  43  44  45  57  …  4965  4966  4967  4972  4973  4974
  6   7   8  49   1   2   3   3  58     5006  5007  5008  5002  5003  5004
  5   6   7  50  50   1   2  53  15     5007  5008  4959  5003  5004  5005
 42  43  44   5  51  51  52  54  10     4958  4959  4960  4965  4966  4967
 43  44  45  10   6  52  53   7  49     4957  4958  5004  4964  4965  4966
  2   3   2   9   4   7   8  14   4  …  5002  5003  4999  5007  5006  5007
 35   1  37  40  11   5   6  13  66     5004  5005  5000  4973  5008  4975
 37  36  39  42  10  12  13  44  50     4997  4998  4966  4971  4972  4973
 51  38  53  58  41  11  12  46  48     4998  4999  4968  4957  4974  4959
  0  52   0   0  43  42  43  62   0     4964  4965  4951     0  4958     0
  ⋮                   ⋮              ⋱                       ⋮        
  0   0   0   0   0   0   0   0   0        0     0     0     0     0     0
  0   0   0   0   0   0   0   0   0        0     0  

------------------------ IDX -------------------------


# Force

## GPU

In [36]:
threads=(16,3)
@cuda(
    threads=threads,
    blocks=(cld.(size(agg.Position,1)+1,threads[1]),1),
    sum_force!(agg.Simulation.Neighbor.idx_red,agg.Simulation.Neighbor.idx_cont,agg.Simulation.Neighbor.idx_sum,agg.Position,agg.Simulation.Force.F,agg.Simulation.Parameter.Force,agg.Simulation.Parameter.Contractile.fₚ,model.Time.dt,1,agg.Simulation.Force.Pol)
)
display(agg.Simulation.Force.Pol)
display(agg.Position)

ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2

evel 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
ERROR: a exception was thrown during kernel execution.
 

CUDA.KernelException: KernelException: exception thrown during kernel execution on device NVIDIA GeForce RTX 3060

In [37]:
agg.Simulation.Force.Pol

5008×3 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
  0.743501     0.110487   -0.222123
 -0.832209    -0.0610624   0.48766
 -0.0562785    0.283213   -0.794147
 -0.00675278  -0.286182   -0.845648
 -0.431435    -0.0878882   0.599355
  0.434986     0.196817   -0.59974
 -0.264799    -0.918297   -0.915607
  0.361635     0.311285   -0.827039
 -0.123037     0.983393   -0.907919
  0.246931     0.61185    -0.863808
  ⋮                       
 -0.524505     0.210155   -0.825064
  0.0777711    0.13864    -0.866565
  0.817628     0.474278   -0.56438
  0.139166     0.184982   -0.972838
  0.037027     0.880951   -0.854039
 -0.736718    -0.530737   -0.287279
  0.06192      0.516411   -0.854099
 -0.100668     0.301082   -0.94827
  0.287406    -0.23556    -0.928391

In [38]:
[sum(agg.Simulation.Force.Pol[1:i,3]) for i =1:69]

69-element Vector{Float32}:
 -0.22212349
  0.2655368
 -0.52860975
 -1.3742573
 -0.7749026
 -1.3746424
 -2.2902493
 -3.1172884
 -4.0252075
 -4.889015
  ⋮
 10.876961
 11.691106
 12.674797
 13.275189
 12.333749
 11.774666
 10.983108
 10.036101
  9.197569

In [39]:
pol_mat = Matrix(agg.Simulation.Force.Pol)

5008×3 Matrix{Float32}:
  0.743501     0.110487   -0.222123
 -0.832209    -0.0610624   0.48766
 -0.0562785    0.283213   -0.794147
 -0.00675278  -0.286182   -0.845648
 -0.431435    -0.0878882   0.599355
  0.434986     0.196817   -0.59974
 -0.264799    -0.918297   -0.915607
  0.361635     0.311285   -0.827039
 -0.123037     0.983393   -0.907919
  0.246931     0.61185    -0.863808
  ⋮                       
 -0.524505     0.210155   -0.825064
  0.0777711    0.13864    -0.866565
  0.817628     0.474278   -0.56438
  0.139166     0.184982   -0.972838
  0.037027     0.880951   -0.854039
 -0.736718    -0.530737   -0.287279
  0.06192      0.516411   -0.854099
 -0.100668     0.301082   -0.94827
  0.287406    -0.23556    -0.928391

In [40]:
qqq = isnan.(pol_mat)

5008×3 BitMatrix:
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 ⋮     
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0

In [41]:
sum(pol_mat[:,3], dims=1)

1-element Vector{Float32}:
 -108.17862

In [42]:
sum(qqq, dims=1)

1×3 Matrix{Int64}:
 0  0  0

In [ ]:
open("unit_vector.xyz", "w") do f
    write(f, "$(Int(size()))\n")
    write(f, "t=$(step * model.Time.dt)\n")
    writedlm(f,hcat(agg.Geometry.outline[1:Int(size(agg.Position,1)/2),:],Matrix(agg.Position[1:Int(size(agg.Position,1)/2),:])), ' ')
end

## CPU

In [43]:
# X_CPU          = Matrix(FusionAGG.Position)
# idx_red_CPU    = Matrix(FusionAGG.Simulation.Neighbor.idx_red)
# idx_cont_CPU   = Matrix(FusionAGG.Simulation.Neighbor.idx_cont)
# force_CPU      = zeros(size(X_CPU))

# Param = vcat(
#         [
#             unique(
#                 getfield(FusionAGG.Simulation.Parameter.Force, fieldnames(Cubic)[i])
#             ) for i=1:size(fieldnames(Cubic),1)
#     ]...)
# Param          = Cubic(Param...)
# A_con          = unique(FusionAGG.Simulation.Parameter.Contractile.fₚ)[1]

# t_knn = 1

In [44]:
# function runCPU()
#     for j = 1:size(idx_red_CPU,1)
#         for i =1:size(X_CPU,1)
#             if idx_red_CPU[j,i] != 0 && idx_red_CPU[j,i] != i
#                 dist = euclidean(X_CPU,i,idx_red_CPU[j,i])
#                 force_CPU[i,:] += force_func(Param,dist) .* (X_CPU[i,:] - X_CPU[idx_red_CPU[j,i],:]) ./ dist
#             end
#         end
#     end

#     for i =1:size(X_CPU,1)
#         if idx_cont_CPU[t_knn,i] != i
#             dist = euclidean(X_CPU,i,idx_cont_CPU[t_knn,i])
#             force_CPU[i,:] += A_con .* (X_CPU[i,:] - X_CPU[idx_cont_CPU[t_knn,i],:]) ./ dist
#         end
#     end
# end

# runCPU()
# display(force_CPU)

## GPU vs CPU

In [45]:
# using Test
# @test Matrix(FusionAGG.Simulation.Force.F) ≈ force_CPU atol=0.01